# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'TriviaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for TriviaApp
  pod 'IQKeyboardManager'
  pod 'KingfisherWebP'
  pod 'PocketSVG'
  pod 'SwiftyGif'
  pod 'PasswordTextField'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Toast-Swift'
  pod 'SkeletonView'
  pod 'ActiveLabel'
  pod 'RSLoadingView'
  pod 'DropDown'
end
